exports.elementsBase={
    cookieTerms:'button[id="onetrust-accept-btn-handler"]',
    searchButton:'button[aria-label="Buscar produto"]',
    searchField:'input[name="search"]',
    showMoreProducts:'span:contains("Ver mais")',
    seeMoreAboutButton:'div[id="buttonCard"]',
    seeMoreAboutTxt:'+ Ver mais',
    buyButton:'span:contains("Comprar")',
    shoppingBagButton:'a[href="/sacola"]',
    continueToBuyButton:'span:contains("Continuar a compra")',
    postalCodeField:'input[name="postalCode"]',
    residenceNumber:'input[name="houseNumber"]',
    addressComplement:'input[name="complement"]',
    addressReference:'input[name="referencePoint"]',
    addressName:'input[name="addressNickname"]',
    saveDeliveryDataButton:'span:contains("Salvar Alterações")',
    finalizeDeliveryDetails:'button[type="submit"][aria-label="Continuar"], span.MuiButton-label:contains("Continuar")',
    validateOrderSuccessfully:'p',
    validateOrderSuccessfullyText:'Pedido finalizado com sucesso e aguardando confirmação de pagamento',
    orderNumberField:'p',
    orderNumberText:'Número do Pedido',
    orderNumber:'h5.MuiTypography-root',
    paymentCodeField:'div.MuiBox-root',
    paymentCodeText:'span.MuiTypography-root.MuiTypography-caption.MuiTypography-colorTextPrimary',
    copyCodePaymentButton:'a.MuiTypography-root.MuiLink-root.MuiLink-underlineHover',
    copyCodePaymentButtonText:'Copiar código',
    copyCodePaymentIcon:'i.material-icons.MuiIcon-root.natds-icons.natds-icons-outlined-action-copy',
    downloadSlipButton:'span:contains("Baixar boleto")',
    formPaymentButton:'button[id="bank-slip"]',
    finalizePurchaseButton:'button[data-gtm-finish-order="true"]'
}