name: Teste Cypress

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configuração do Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install

    - name: Executar testes Cypress
      run: npm test
